In [ ]:
#importar datasets de proves y splitter alemany
!pip install datasets evaluate --upgrade
!python -m spacy download de_core_news_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 25.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('de_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
import re
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np
import spacy
import datasets
import torchtext
import tqdm
import evaluate

Creem un dataset a partir del txt que serà un diccionari amb les claus dels idiomes (en i de) i com a valor una llista de les frases traduïdes en ordre

In [ ]:
def eliminar_ccby(linea):
    indice_ccby = linea.find("CC-BY")
    if indice_ccby != -1:
        return linea[:indice_ccby]
    return linea

def separar_frases(linea):
    patron = r'(.+?[.!?])\s+([^A-Z]?[\s]+)?(.+)?'
    coincidencias = re.match(patron, linea)
    if coincidencias:
        frase1 = coincidencias.group(1)
        frase2 = coincidencias.group(3)
        return frase1.strip(), frase2.strip() if frase2 else None
    else:
        return None, None

def make_dataset(archivo_entrada):
    dataset = []
    with open(archivo_entrada, 'r') as f_in:
        for linea in f_in:
            linea_clean = eliminar_ccby(linea)
            a,b = separar_frases(linea_clean)
            dataset.append({'en':a,'de':b})
    return dataset

archivo_entrada = 'deu.txt'
data = make_dataset(archivo_entrada)

In [ ]:
print(data[:10])

[{'en': 'Go.', 'de': 'Geh.'}, {'en': 'Hi.', 'de': 'Hallo!'}, {'en': 'Hi.', 'de': 'Grüß Gott!'}, {'en': 'Run!', 'de': 'Lauf!'}, {'en': 'Run.', 'de': 'Lauf!'}, {'en': 'Wow!', 'de': 'Potzdonner!'}, {'en': 'Wow!', 'de': 'Donnerwetter!'}, {'en': 'Duck!', 'de': 'Kopf runter!'}, {'en': 'Fire!', 'de': 'Feuer!'}, {'en': 'Help!', 'de': 'Hilfe!'}]


Importem splitters d'anglés i alemany

In [ ]:
en_nlp = spacy.load("en_core_web_sm")
de_nlp = spacy.load("de_core_news_sm")

In [ ]:
string = "What a lovely day it is today!"
[token.text for token in en_nlp.tokenizer(string)]

['What', 'a', 'lovely', 'day', 'it', 'is', 'today', '!']

Para cada par de oraciones añadimos a más su split correspondiente con el incio y fin de frase y tenemos en cuenta las mayúsculas

In [ ]:
def tokenize_example(data, en_nlp, de_nlp, max_length, lower, sos_token, eos_token):
    for i in range(len(data)):
        en_tokens = [token.text for token in en_nlp.tokenizer(data[i]["en"])][:max_length]
        de_tokens = [token.text for token in de_nlp.tokenizer(data[i]["de"])][:max_length]
        if lower:
            en_tokens = [token.lower() for token in en_tokens]
            de_tokens = [token.lower() for token in de_tokens]
        en_tokens = [sos_token] + en_tokens + [eos_token]
        de_tokens = [sos_token] + de_tokens + [eos_token]
        data[i]['en_tokens'] = en_tokens
        data[i]['de_tokens'] = de_tokens
    return data

In [ ]:
train = data[:1000]
max_length = 1000
lower = True
sos_token = "<sos>"
eos_token = "<eos>"

fn_kwargs = {
    "example": train,
    "en_nlp": en_nlp,
    "de_nlp": de_nlp,
    "max_length": max_length,
    "lower": lower,
    "sos_token": sos_token,
    "eos_token": eos_token,
}
inputs = [train,en_nlp,de_nlp,max_length,lower,sos_token,eos_token]

sos = start of sentence,
eos = end of sentence,
unk = unknown,
pad = padding

In [ ]:
train = tokenize_example(*inputs)
train[0]

{'en': 'Go.',
 'de': 'Geh.',
 'en_tokens': ['<sos>', 'go', '.', '<eos>'],
 'de_tokens': ['<sos>', 'geh', '.', '<eos>']}

In [ ]:
min_freq = 2
unk_token = "<unk>"
pad_token = "<pad>"

special_tokens = [
    unk_token,
    pad_token,
    sos_token,
    eos_token,
]


all_en_tokens, all_de_tokens = [], []
for frase in train:
    all_en_tokens.append(frase['en_tokens'])
    all_de_tokens.append(frase['de_tokens'])

en_vocab = torchtext.vocab.build_vocab_from_iterator(
    all_en_tokens,
    min_freq=min_freq,
    specials=special_tokens,
)

de_vocab = torchtext.vocab.build_vocab_from_iterator(
    all_de_tokens,
    min_freq=min_freq,
    specials=special_tokens,
)

In [ ]:
words_en, words_de = en_vocab.get_itos(), de_vocab.get_itos()
len(words_en), len(words_de)

(262, 297)

In [ ]:
assert en_vocab[unk_token] == de_vocab[unk_token]
assert en_vocab[pad_token] == de_vocab[pad_token]

unk_index = en_vocab[unk_token]
pad_index = en_vocab[pad_token]

en_vocab.set_default_index(unk_index)
de_vocab.set_default_index(unk_index)

In [ ]:
"man" in words_en

True

In [ ]:
def numericalize_example(data, en_vocab, de_vocab):
    for i in range(len(data)):
        en_ids = en_vocab.lookup_indices(data[i]["en_tokens"])
        de_ids = de_vocab.lookup_indices(data[i]["de_tokens"])
        data[i]['en_ids'] = en_ids
        data[i]['de_ids'] = de_ids
    return data

In [ ]:
train = numericalize_example(train, en_vocab, de_vocab)
train[100]

{'en': 'No way!',
 'de': 'Das kommt nicht in Frage!',
 'en_tokens': ['<sos>', 'no', 'way', '!', '<eos>'],
 'de_tokens': ['<sos>', 'das', 'kommt', 'nicht', 'in', 'frage', '!', '<eos>'],
 'en_ids': [2, 59, 90, 7, 3],
 'de_ids': [2, 16, 71, 21, 43, 0, 5, 3]}

L'equivalència token - índex és correcte

In [ ]:
print(train[100]["en_tokens"])
print(en_vocab.lookup_tokens(train[100]["en_ids"]))
train[100]["en_tokens"] == en_vocab.lookup_tokens(train[100]["en_ids"])

['<sos>', 'no', 'way', '!', '<eos>']
['<sos>', 'no', 'way', '!', '<eos>']


True

In [ ]:
for i in range(len(train)):
    en_ids = train[i]['en_ids']
    de_ids = train[i]['de_ids']
    train[i]['en_ids'] = torch.tensor(en_ids)
    train[i]['de_ids'] = torch.tensor(de_ids)
train[100]

{'en': 'No way!',
 'de': 'Das kommt nicht in Frage!',
 'en_tokens': ['<sos>', 'no', 'way', '!', '<eos>'],
 'de_tokens': ['<sos>', 'das', 'kommt', 'nicht', 'in', 'frage', '!', '<eos>'],
 'en_ids': tensor([ 2, 59, 90,  7,  3]),
 'de_ids': tensor([ 2, 16, 71, 21, 43,  0,  5,  3])}

Ara ja tenim el dataset amb totes les des necessàries per començar el entrenament del model

In [ ]:
lista_grande = [i*3 for i in range(100)]

import h5py

# Guardar la lista en un archivo HDF5
with h5py.File('datos.h5', 'w') as f:
    f.create_dataset('lista', data=lista_grande)

# Recuperar la lista del archivo HDF5
with h5py.File('datos.h5', 'r') as f:
    lista_grande_recuperada = f['lista'][:]


lista_grande_recuperada

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
       234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270,
       273, 276, 279, 282, 285, 288, 291, 294, 297])

In [ ]:
import torch
import torch.nn as nn

# Supongamos que tenemos un vocabulario de tamaño 10 y queremos vectores de embedding de dimensión 5
vocab_size = 10
embedding_dim = 5

# Creamos una capa de embedding con el tamaño de vocabulario y la dimensión del embedding especificados
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Creamos una secuencia de entrada de índices
input_indices = torch.tensor([1, 3, 5, 7, 9])

# Pasamos la secuencia de entrada a través de la capa de embedding
embedded_vectors = embedding_layer(input_indices)

# Mostramos los vectores de embedding resultantes
print("Vectores de embedding:")
print(embedded_vectors)

Vectores de embedding:
tensor([[ 0.3530, -2.1909,  0.5289, -0.8239, -1.4213],
        [ 0.3565,  1.1609, -1.1227, -1.1443, -1.5309],
        [-0.6661, -1.3697, -1.3740,  0.5193,  0.7109],
        [ 0.1386, -0.5379,  0.7494,  0.6972, -0.1818],
        [ 1.5970, -1.0652,  0.5939,  0.3656,  1.2412]],
       grad_fn=<EmbeddingBackward0>)


Creem una classe básica dicionari per crear el dataloader de la llibreria torch

In [ ]:
import torch
from torch.utils.data import Dataset

class ListDictDataset(Dataset):
    def __init__(self, list_of_dicts):
        self.list_of_dicts = list_of_dicts

    def __len__(self):
        return len(self.list_of_dicts)

    def __getitem__(self, index):
        return self.list_of_dicts[index]

dataset = train
#dataset = ListDictDataset(train)
type(dataset)

list

Creem un dataloader per processar bé totes les traduccions, on només afegirem els index de les paraules al diccionari corresponent segons l idioma, que és el que ens servirà per fer l embedding de les frases

In [ ]:
def get_collate_fn(pad_index):
    def collate_fn(batch):
        batch_en_ids = [example["en_ids"] for example in batch]
        batch_de_ids = [example["de_ids"] for example in batch]
        batch_en_ids = nn.utils.rnn.pad_sequence(batch_en_ids, padding_value=pad_index)  #Fem servir padding com relleno
        batch_de_ids = nn.utils.rnn.pad_sequence(batch_de_ids, padding_value=pad_index)
        batch = {
            "en_ids": batch_en_ids,
            "de_ids": batch_de_ids,
        }
        return batch

    return collate_fn

In [ ]:
def get_data_loader(dataset, batch_size, pad_index, shuffle=False):
    collate_fn = get_collate_fn(pad_index)
    data_loader = torch.utils.data.DataLoader(
        dataset=dataset,
        batch_size=batch_size,
        collate_fn=collate_fn,
        shuffle=shuffle,
    )
    return data_loader

In [ ]:
batch_size = 128
train_data_loader = get_data_loader(dataset, batch_size, pad_index, shuffle=True)

In [ ]:
train_data_loader

Cla

In [ ]:
class Encoder(nn.Module):
    def __init__(self, input_dim, embedding_dim, encoder_hidden_dim, decoder_hidden_dim, dropout):
        super().__init__()
        self.embedding = nn.Embedding(input_dim, embedding_dim)
        self.rnn = nn.GRU(embedding_dim, encoder_hidden_dim, bidirectional=True)
        self.fc = nn.Linear(encoder_hidden_dim * 2, decoder_hidden_dim)
        self.dropout = nn.Dropout(dropout)  # recordem: dropout desactiva un % de neurones i així evita l'overfitting

    def forward(self, src):
        # src = [src length, batch size]
        embedded = self.dropout(self.embedding(src))
        # embedded = [src length, batch size, embedding dim]
        outputs, hidden = self.rnn(embedded)
        # outputs = [src length, batch size, hidden dim * n directions]
        # hidden = [n layers * n directions, batch size, hidden dim]
        # hidden is stacked [forward_1, backward_1, forward_2, backward_2, ...]
        # outputs are always from the last layer
        # hidden [-2, :, : ] is the last of the forwards RNN
        # hidden [-1, :, : ] is the last of the backwards RNN
        # initial decoder hidden is final hidden state of the forwards and backwards
        # encoder RNNs fed through a linear layer
        hidden = torch.tanh(
            self.fc(torch.cat((hidden[-2, :, :], hidden[-1, :, :]), dim=1))
        )
        # outputs = [src length, batch size, encoder hidden dim * 2]
        # hidden = [batch size, decoder hidden dim]
        return outputs, hidden

In [ ]:
class Attention(nn.Module):
    def __init__(self, encoder_hidden_dim, decoder_hidden_dim):
        super().__init__()
        self.attn_fc = nn.Linear(
            (encoder_hidden_dim * 2) + decoder_hidden_dim, decoder_hidden_dim
        )
        self.v_fc = nn.Linear(decoder_hidden_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        # hidden = [batch size, decoder hidden dim]
        # encoder_outputs = [src length, batch size, encoder hidden dim * 2]
        batch_size = encoder_outputs.shape[1]
        src_length = encoder_outputs.shape[0]
        # repeat decoder hidden state src_length times
        hidden = hidden.unsqueeze(1).repeat(1, src_length, 1)
        encoder_outputs = encoder_outputs.permute(1, 0, 2)
        # hidden = [batch size, src length, decoder hidden dim]
        # encoder_outputs = [batch size, src length, encoder hidden dim * 2]
        energy = torch.tanh(self.attn_fc(torch.cat((hidden, encoder_outputs), dim=2)))
        # energy = [batch size, src length, decoder hidden dim]
        attention = self.v_fc(energy).squeeze(2)
        # attention = [batch size, src length]
        return torch.softmax(attention, dim=1)

In [ ]:
class Decoder(nn.Module):
    def __init__(
        self,
        output_dim,
        embedding_dim,
        encoder_hidden_dim,
        decoder_hidden_dim,
        dropout,
        attention,
    ):
        super().__init__()
        self.output_dim = output_dim
        self.attention = attention
        self.embedding = nn.Embedding(output_dim, embedding_dim)
        self.rnn = nn.GRU((encoder_hidden_dim * 2) + embedding_dim, decoder_hidden_dim)
        self.fc_out = nn.Linear(
            (encoder_hidden_dim * 2) + decoder_hidden_dim + embedding_dim, output_dim
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, input, hidden, encoder_outputs):
        # input = [batch size]
        # hidden = [batch size, decoder hidden dim]
        # encoder_outputs = [src length, batch size, encoder hidden dim * 2]
        input = input.unsqueeze(0)
        # input = [1, batch size]
        embedded = self.dropout(self.embedding(input))
        # embedded = [1, batch size, embedding dim]
        a = self.attention(hidden, encoder_outputs)
        # a = [batch size, src length]
        a = a.unsqueeze(1)
        # a = [batch size, 1, src length]
        encoder_outputs = encoder_outputs.permute(1, 0, 2)
        # encoder_outputs = [batch size, src length, encoder hidden dim * 2]
        weighted = torch.bmm(a, encoder_outputs)
        # weighted = [batch size, 1, encoder hidden dim * 2]
        weighted = weighted.permute(1, 0, 2)
        # weighted = [1, batch size, encoder hidden dim * 2]
        rnn_input = torch.cat((embedded, weighted), dim=2)
        # rnn_input = [1, batch size, (encoder hidden dim * 2) + embedding dim]
        output, hidden = self.rnn(rnn_input, hidden.unsqueeze(0))
        # output = [seq length, batch size, decoder hid dim * n directions]
        # hidden = [n layers * n directions, batch size, decoder hid dim]
        # seq len, n layers and n directions will always be 1 in this decoder, therefore:
        # output = [1, batch size, decoder hidden dim]
        # hidden = [1, batch size, decoder hidden dim]
        # this also means that output == hidden
        assert (output == hidden).all()
        embedded = embedded.squeeze(0)
        output = output.squeeze(0)
        weighted = weighted.squeeze(0)
        prediction = self.fc_out(torch.cat((output, weighted, embedded), dim=1))
        # prediction = [batch size, output dim]
        return prediction, hidden.squeeze(0), a.squeeze(1)

In [ ]:
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device

    def forward(self, src, trg, teacher_forcing_ratio):
        # src = [src length, batch size]
        # trg = [trg length, batch size]
        # teacher_forcing_ratio is probability to use teacher forcing
        # e.g. if teacher_forcing_ratio is 0.75 we use teacher forcing 75% of the time
        batch_size = src.shape[1]
        trg_length = trg.shape[0]
        trg_vocab_size = self.decoder.output_dim
        # tensor to store decoder outputs
        outputs = torch.zeros(trg_length, batch_size, trg_vocab_size).to(self.device)
        # encoder_outputs is all hidden states of the input sequence, back and forwards
        # hidden is the final forward and backward hidden states, passed through a linear layer
        encoder_outputs, hidden = self.encoder(src)
        # outputs = [src length, batch size, encoder hidden dim * 2]
        # hidden = [batch size, decoder hidden dim]
        # first input to the decoder is the <sos> tokens
        input = trg[0, :]
        for t in range(1, trg_length):
            # insert input token embedding, previous hidden state and all encoder hidden states
            # receive output tensor (predictions) and new hidden state
            output, hidden, _ = self.decoder(input, hidden, encoder_outputs)
            # output = [batch size, output dim]
            # hidden = [n layers, batch size, decoder hidden dim]
            # place predictions in a tensor holding predictions for each token
            outputs[t] = output
            # decide if we are going to use teacher forcing or not
            teacher_force = random.random() < teacher_forcing_ratio
            # get the highest predicted token from our predictions
            top1 = output.argmax(1)
            # if teacher forcing, use actual next token as next input
            # if not, use predicted token
            input = trg[t] if teacher_force else top1
            # input = [batch size]
        return outputs

Valors amb el que anirem probant per millorar l'eficiència del model

In [ ]:
input_dim = len(de_vocab)
output_dim = len(en_vocab)
encoder_embedding_dim = 256
decoder_embedding_dim = 256
encoder_hidden_dim = 512
decoder_hidden_dim = 512
encoder_dropout = 0.5
decoder_dropout = 0.5
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

attention = Attention(encoder_hidden_dim, decoder_hidden_dim)

encoder = Encoder(
    input_dim,
    encoder_embedding_dim,
    encoder_hidden_dim,
    decoder_hidden_dim,
    encoder_dropout,
)

decoder = Decoder(
    output_dim,
    decoder_embedding_dim,
    encoder_hidden_dim,
    decoder_hidden_dim,
    decoder_dropout,
    attention,
)

model = Seq2Seq(encoder, decoder, device).to(device)

Cada paràmetre representa el weight o bias d'una capa (ih=input, hh=hidden) en el recorregut d'anada per calcular el loss o el de tornada que actualitza el gradient (reverse)

In [ ]:
for p in model.named_parameters(): print(p)

('encoder.embedding.weight', Parameter containing:
tensor([[ 2.1168e-03, -8.8684e-03, -3.3382e-04,  ..., -1.6067e-02,
          2.2180e-02, -1.2415e-02],
        [-1.0009e-02,  9.2787e-03, -2.7888e-03,  ...,  1.3415e-03,
          1.1938e-02,  2.9915e-03],
        [-2.5358e-03, -7.9588e-04, -1.7207e-02,  ..., -6.2139e-03,
          1.7234e-02,  1.9419e-02],
        ...,
        [-2.1381e-03, -3.7756e-03, -6.6067e-03,  ...,  9.5179e-04,
          1.5396e-02,  8.8129e-03],
        [-3.1412e-05,  4.6364e-03, -9.6797e-03,  ...,  1.3090e-02,
          1.5145e-02,  5.9216e-04],
        [ 2.5885e-03, -2.4042e-03,  4.5074e-03,  ...,  7.3129e-03,
         -1.5921e-02, -8.8536e-03]], requires_grad=True))
('encoder.rnn.weight_ih_l0', Parameter containing:
tensor([[ 1.2817e-02, -1.0834e-02,  1.7849e-03,  ..., -1.0800e-02,
          8.9175e-05, -6.6825e-04],
        [ 1.1681e-02,  1.5100e-02, -2.4064e-03,  ...,  1.4649e-02,
          3.9045e-03, -2.0727e-03],
        [ 1.2053e-02, -5.7004e-03, -1.3

In [ ]:
def init_weights(m):
    for name, param in m.named_parameters():
        if "weight" in name:
            nn.init.normal_(param.data, mean=0, std=0.01)  # pesos molt propers a 0, desviació del 1%, perill de vanishing
        else:
            nn.init.constant_(param.data, 0)

model.apply(init_weights)

Seq2Seq(
  (encoder): Encoder(
    (embedding): Embedding(297, 256)
    (rnn): GRU(256, 512, bidirectional=True)
    (fc): Linear(in_features=1024, out_features=512, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
  (decoder): Decoder(
    (attention): Attention(
      (attn_fc): Linear(in_features=1536, out_features=512, bias=True)
      (v_fc): Linear(in_features=512, out_features=1, bias=False)
    )
    (embedding): Embedding(262, 256)
    (rnn): GRU(1280, 512)
    (fc_out): Linear(in_features=1792, out_features=262, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
)

In [ ]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad),model.parameters()

a,b = count_parameters(model)
suma=0
for x in b:
  print(x)

print(f"The model has {a:,} trainable parameters",suma)

Parameter containing:
tensor([[ 2.1168e-03, -8.8684e-03, -3.3382e-04,  ..., -1.6067e-02,
          2.2180e-02, -1.2415e-02],
        [-1.0009e-02,  9.2787e-03, -2.7888e-03,  ...,  1.3415e-03,
          1.1938e-02,  2.9915e-03],
        [-2.5358e-03, -7.9588e-04, -1.7207e-02,  ..., -6.2139e-03,
          1.7234e-02,  1.9419e-02],
        ...,
        [-2.1381e-03, -3.7756e-03, -6.6067e-03,  ...,  9.5179e-04,
          1.5396e-02,  8.8129e-03],
        [-3.1412e-05,  4.6364e-03, -9.6797e-03,  ...,  1.3090e-02,
          1.5145e-02,  5.9216e-04],
        [ 2.5885e-03, -2.4042e-03,  4.5074e-03,  ...,  7.3129e-03,
         -1.5921e-02, -8.8536e-03]], requires_grad=True)
Parameter containing:
tensor([[ 1.2817e-02, -1.0834e-02,  1.7849e-03,  ..., -1.0800e-02,
          8.9175e-05, -6.6825e-04],
        [ 1.1681e-02,  1.5100e-02, -2.4064e-03,  ...,  1.4649e-02,
          3.9045e-03, -2.0727e-03],
        [ 1.2053e-02, -5.7004e-03, -1.3056e-02,  ..., -1.3039e-02,
          4.1758e-03, -1.1200e-

In [ ]:
optimizer = optim.Adam(model.parameters())
criterion = nn.CrossEntropyLoss(ignore_index=pad_index)

In [ ]:
for i in range(len(train)):
  lista = train[i]['de_ids']
  print(lista)

tensor([ 2, 27,  4,  3])
tensor([ 2, 99,  5,  3])
tensor([2, 0, 0, 5, 3])
tensor([  2, 146,   5,   3])
tensor([  2, 146,   5,   3])
tensor([2, 0, 5, 3])
tensor([2, 0, 5, 3])
tensor([  2, 240, 112,   5,   3])
tensor([  2, 132,   5,   3])
tensor([2, 0, 5, 3])
tensor([ 2, 25,  0,  5,  3])
tensor([ 2,  0, 12,  5,  3])
tensor([  2, 178,  50,   5,   3])
tensor([  2, 194,   5,   3])
tensor([2, 0, 5, 3])
tensor([2, 0, 5, 3])
tensor([ 2, 88,  5,  3])
tensor([ 2, 88,  4,  3])
tensor([ 2, 97, 35,  4,  3])
tensor([  2, 247,   7,   5,   3])
tensor([  2, 279,   7,   4,   3])
tensor([  2,  17, 185,   4,   3])
tensor([ 2, 99,  5,  3])
tensor([2, 0, 5, 3])
tensor([ 2, 99,  5,  3])
tensor([  2, 119,  12,   5,   3])
tensor([  2, 264,   5,   3])
tensor([  2,   6, 282,  18,   4,   3])
tensor([  2,   6,  14,  18, 178,   4,   3])
tensor([  2,   6, 110,   4,   3])
tensor([  2,   6, 179,   4,   3])
tensor([  2, 186,   4,   3])
tensor([2, 6, 0, 7, 4, 3])
tensor([2, 6, 0, 7, 4, 3])
tensor([  2,   6, 226,  37,   

Totes les primeres files de cada batch estan plenes de 2, com l'inici de tots els en_ids o de_ids, que representa el eos

In [ ]:
loader = train_data_loader
a,b = 0,0

for batch in loader:
  print(batch['en_ids'])

num_batches = len(loader)
print(f'Número de batches: {num_batches}')  #número de batches dins del loader

tensor([[  2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2],
        [ 55,   5,   6,  49,  10,  97,   5,  11, 140,   5,   5,   5,  11,  18,
           5,   0, 161,   5,  94,  38,  10,  30,  11,  79, 113,   5,   5,  87,
           6,   5,   5,   5,  10,   5,   5,   6,   0, 124,   5, 162, 157, 197,
          26,   5,  96,   9,  10

In [ ]:
def train_seq2seq(
    model, data_loader, optimizer, criterion, clip, teacher_forcing_ratio, device
):
    model.train()
    epoch_loss = 0
    for i, batch in enumerate(data_loader):
        src = batch["de_ids"].to(device)   # device és gpu collab ja que és on fem les probes per no gasta hores de mv azure
        trg = batch["en_ids"].to(device)
        # src = [src length, batch size]
        # trg = [trg length, batch size]
        optimizer.zero_grad()
        output = model(src, trg, teacher_forcing_ratio)
        # output = [trg length, batch size, trg vocab size]
        output_dim = output.shape[-1]
        output = output[1:].view(-1, output_dim)
        # output = [(trg length - 1) * batch size, trg vocab size]
        trg = trg[1:].view(-1)
        # trg = [(trg length - 1) * batch size]
        loss = criterion(output, trg)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        optimizer.step()
        epoch_loss += loss.item()
    return epoch_loss / len(data_loader)

def evaluate_seq2seq(model, data_loader, criterion, device):
    model.eval()
    epoch_loss = 0
    with torch.no_grad():
        for i, batch in enumerate(data_loader):
            src = batch["de_ids"].to(device)
            trg = batch["en_ids"].to(device)
            # src = [src length, batch size]
            # trg = [trg length, batch size]
            output = model(src, trg, 0)  # turn off teacher forcing
            # output = [trg length, batch size, trg vocab size]
            output_dim = output.shape[-1]
            output = output[1:].view(-1, output_dim)
            # output = [(trg length - 1) * batch size, trg vocab size]
            trg = trg[1:].view(-1)
            # trg = [(trg length - 1) * batch size]
            loss = criterion(output, trg)
            epoch_loss += loss.item()
    return epoch_loss / len(data_loader)

In [ ]:
n_epochs = 2
clip = 1.0
teacher_forcing_ratio = 0.5

best_valid_loss = float("inf")

for epoch in tqdm.tqdm(range(n_epochs)):  #tqdm per veure el processament del bucle, ja que tardará molt
    train_loss = train_seq2seq(
        model,
        train_data_loader,
        optimizer,
        criterion,
        clip,
        teacher_forcing_ratio,
        device,
    )
    valid_loss = evaluate_seq2seq(
        model,
        valid_data_loader,
        criterion,
        device,
    )
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), "tut3-model.pt")
    print(f"\tTrain Loss: {train_loss:7.3f} | Train PPL: {np.exp(train_loss):7.3f}")
    print(f"\tValid Loss: {valid_loss:7.3f} | Valid PPL: {np.exp(valid_loss):7.3f}")

  0%|          | 0/2 [00:12<?, ?it/s]


NameError: name 'valid_data_loader' is not defined